### PR TITLE
added code to use secrets from docker image to login to synapse

### LINKED ISSUE #3: modify r script to use secrets to login

### PR DESCRIPTION
**Pull request by andrewelamb**
fixes #3

### CODE REVIEW

**Review by thomasyu888 — APPROVED** [review]
This works as long as your secret key is PAT

**Comment by andrewelamb** [comment]
Would the secret key ever be named something else? The name value pairs come from AWS correct?

**Comment by thomasyu888** [comment]
The secret `SCHEDULED_JOB_SECRETS` always stays the same, but you specify your own secret value

**Comment by andrewelamb** [comment]
@thomasyu888 Oh right that make sense, it will be the name of the secret for the synapse PAT in this repo correct?

**Comment by andrewelamb** [comment]
@jaybee84 We'll need a synapse PAT, that can access the the NF fileviews and tables that make up the source data, and the two directories we store the RDS files. Is there something like a NF service account we could use?

**Comment by andrewelamb** [comment]
@thomasyu888 Should the synapse pat secret be "PAT", or should it be more specific like "SYNAPSE_PAT"?

**Comment by thomasyu888** [comment]
We have been using SYNAPSE_AUTH_TOKEN

**Comment by jaybee84** [comment]
@andrewelamb : We should use the nf-service account for this

**Comment by andrewelamb** [comment]
@jaybee84 I created a secret called SYNAPSE_AUTH_TOKEN, could you assign it the value of a token associated with the service account?

**Comment by andrewelamb** [comment]
@thomasyu888 Is there anything else that needs to be done to the script?

**Comment by thomasyu888** [comment]
Nope LGTM!

**Pull request merged**
